Отрисуй меня полностью 2(проблема с комментариями)
htmlacademy-javascript/1839371-kekstagram-25 pull request #6
Opened 2022-03-14 12:21 UTC by MalskyKirill

2022-03-14 13:17 UTC, ekazakov requested changes

2022-03-14 13:17 UTC, ekazakov commented on js/pictures.js
> +    for (let photo of similarPhotos) {
Ты проходишься по всем фоткам и у каждой берешь комментарии. Тебе нужно получать брать комменты только из фотки по которой кликнули

При генерации картинки в нее можно записать атрибут с id `pictureElement.dataset.id = photo.id`

А в обработчике клика по превьюшек можно будет получить этот id — `thumbnail.dataset.id` и по нему найти нужную фотографию в массиве similarPhotos

2022-03-14 23:10 UTC, ekazakov requested changes

2022-03-14 23:10 UTC, ekazakov commented on js/pictures.js
> +    similarPhotos[id].comments.forEach(({avatar, name, message}) => {
Тут получается, что ты используешь id как порядковый номер в массиве. Но массив нумеруется с 0, а идентификаторы с 1. Из-за этого, скорей всего, проблема и с неверным количеством комментариев.

Можно сделать так: `similarPhotos[id-1].comments....`
Или использовать метод find `similarPhotos.find((photo) => photo.id === id)` 
https://learn.javascript.ru/array-methods#find-i-findindex

2022-03-15 07:53 UTC, MalskyKirill commented on js/pictures.js
> +    similarPhotos[id].comments.forEach(({avatar, name, message}) => {
У меня получается что номера не на один отличаются а вообще рандомно идут, а метод find возвращает undefided.

2022-03-15 09:15 UTC, merged